version: "3"

services:
  web:
    build: ./web
    image: web
    pull_policy: never
    container_name: web
    restart: always
    ports:
      - "5173:5173"
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      NODE_ENV: dev
    networks:
      - net
    volumes:
      - ./web:/usr/src/app
    tty: true
  db:
    build: ./database
    image: database
    pull_policy: never
    container_name: database
    env_file:
      - ./.env
    restart: always
    expose:
      - "5432"
    networks:
      - net
    tty: true

networks:
  net:
    driver: bridge
