version: "3"

services:
  web:
    build: 
      context: ./web
      args:
        NODE_ENV: development
    image: web
    container_name: web
    restart: always
    ports:
      - "5173:5173"
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - net
    volumes:
      - ./web:/usr/src/app
    tty: true
    command: sh -c "/usr/src/app/init.sh"
  database:
    build: ./database
    image: database
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    container_name: database
    restart: always
    expose:
      - "5432"
    networks:
      - net
    tty: true

networks:
  net:
    driver: bridge
