FROM postgres

COPY ./postgresql.conf 	/etc/postgresql/postgresql.conf

# ENTRYPOINT ["postgres"]

# ENTRYPOINT ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
ENTRYPOINT ["docker-entrypoint.sh", "-c", "config_file=/etc/postgresql/postgresql.conf"]

